title: My BlogPosts
author: Michel van Veldhoven
email: m.vanveldhoven@hotmail.com
description: this blog post is about serverless programming
theme: minima

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
